create table if not exists public.kpi_records (
  id bigint generated by default as identity primary key,
  data date not null,
  source_sheet text not null,
  faturamento numeric(14, 2) not null default 0,
  lucro numeric(14, 2) not null default 0,
  roi numeric(10, 2) not null default 0,
  cpa numeric(10, 2) not null default 0,
  cpl numeric(10, 2) not null default 0,
  leads integer not null default 0,
  vendas integer not null default 0,
  margem numeric(10, 2) not null default 0,
  investimento_ads numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  data date not null,
  source_sheet text not null,
  tipo text not null,
  descricao text not null,
  severidade text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_kpi_records_data on public.kpi_records (data);
create index if not exists idx_kpi_records_source_sheet on public.kpi_records (source_sheet);
create index if not exists idx_incidents_data on public.incidents (data);
create index if not exists idx_incidents_source_sheet on public.incidents (source_sheet);
create index if not exists idx_incidents_severidade on public.incidents (severidade);

alter table public.kpi_records enable row level security;
alter table public.incidents enable row level security;

drop policy if exists "Allow public read kpi records" on public.kpi_records;
create policy "Allow public read kpi records"
on public.kpi_records
for select
to anon
using (true);

drop policy if exists "Allow public read incidents" on public.incidents;
create policy "Allow public read incidents"
on public.incidents
for select
to anon
using (true);
